name: counterfactual_icu_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - lightning
  - matplotlib
  - pandas
  - plotly
  - numpy
  - wandb
  - scipy
  - python-kaleido
  - pip:
      # PyTorch will auto-detect platform and install appropriate version
      - torch
      - torchvision
      - torchaudio
      - git+https://github.com/rtqichen/torchdiffeq
      - torchsde
      - pyyaml
      - ruff
