base_path: "/Users/riccardoconci/Local_documents/!!MIMIC"
temp_path: "../temp_dfs"
min_admit_duration: 2
max_admit_duration: 10
min_icu_los_days: 1 # Minimum ICU length of stay in days
MAP_itemid: 220052 # itemid for Mean Arterial Pressure
top_n_physio_features: 80
physio_categories_to_keep:
  - "Routine Vital Signs"
  - "Respiratory"
  - "Labs"
  - "Neurological"
  - "Hemodynamics"
chunk_size: 1000000
use_cache: true
