python src_new/models/hybrid_sde_main.py -m \
  trainer.accelerator=gpu trainer.devices=4 trainer.strategy=ddp_find_unused_parameters_true \
  trainer.precision=bf16-mixed trainer.accumulate_grad_batches=1 \
  trainer.max_epochs=25 \
  model.plot_outputs_train=true model.plot_every=15 \
  data.batch_size=16 \
  model.controller_type=mlp \
  model.learning_rate=1e-4,5e-4 \
  seed=64 \
  model.use_encoder= raindrop, none \
  model.num_samples=3 \
  model.loss_type=nll \
  model.log_lik_scale_mode=annealing


python src_new/models/hybrid_sde_main.py -m \
  trainer.accelerator=gpu trainer.devices=4 trainer.strategy=ddp_find_unused_parameters_true \
  trainer.precision=bf16-mixed trainer.accumulate_grad_batches=1 \
  trainer.max_epochs=10 trainer.limit_train_batches=1.0 trainer.overfit_batches=0.0 \
  model.plot_outputs_train=true model.plot_every=10 \
  data.batch_size=64 \
  model.controller_type=mlp,gat \
  model.learning_rate=1e-5,5e-5 \
  seed=64 \
  model.use_encoder=none,raindrop \
  model.num_samples=1 \ 
  model.loss_type=mse \
  model.log_lik_scale_mode=fixed