python src_new/models/hybrid_sde_main.py -m \
  trainer.accelerator=gpu trainer.devices=4 trainer.strategy=ddp_find_unused_parameters_true \
  trainer.precision=bf16-mixed trainer.accumulate_grad_batches=2 \
  trainer.max_epochs=10 trainer.limit_train_batches=1.0 trainer.overfit_batches=1.0 \
  model.plot_outputs_train=false model.plot_every=1000000 \
  data.batch_size=32,64 \
  model.controller_type=mlp,gat \
  model.learning_rate=1e-5,3e-5,1e-4 \
  seed=13,47,64 \
  model.use_encoder=none,raindrop \
  model.num_samples=1,3