name: expLight
channels:
  - conda-forge
  - defaults
dependencies:
  - lightning
  - matplotlib
  - pandas
  - plotly
  - wandb
  - scipy
  - pip:
      - git+https://github.com/rtqichen/torchdiffeq
      - torchsde
