wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.5
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714294237.0
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.11.9
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
input_dim:
  desc: null
  value: 2
output_dim:
  desc: null
  value: 1
hidden_dim:
  desc: null
  value: 32
latent_dim:
  desc: null
  value: 8
use_whole_trajectory:
  desc: null
  value: true
post_tx_ode_len:
  desc: null
  value: 14
Tx_dim:
  desc: null
  value: 1
theta:
  desc: null
  value: 0.1
mu:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.002
